# Generated by Django 5.1.2 on 2024-10-31 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='beginner', max_length=20)),
                ('gameState', models.CharField(choices=[('unknown', 'Unknown'), ('opening', 'Opening'), ('midgame', 'Midgame'), ('endgame', 'Endgame')], default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.board')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('symbol', models.CharField(choices=[('X', 'X'), ('O', 'O'), ('', 'Empty')], default='', max_length=20)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.line')),
            ],
        ),
    ]
