# Generated by Django 5.1.2 on 2025-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
