# Generated by Django 5.1.2 on 2024-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='board',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
