# Generated by Django 5.1.2 on 2025-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customuser_is_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="anonymousToken",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="gameCode",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.TextField(),
        ),
    ]
