# Generated by Django 5.1.2 on 2025-02-12 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_board_uuid_alter_customuser_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameStatus",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("elo", models.IntegerField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("win", "Win"),
                            ("lose", "Lose"),
                            ("draw", "Draw"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(choices=[("X", "X"), ("O", "O")], max_length=1),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("elodifference", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_status",
                        to="api.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MultiplayerGame",
        ),
    ]
