# Generated by Django 5.1.2 on 2025-02-21 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_game_anonymoustoken_game_gamecode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryUsers",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
