# Generated by Django 5.1.2 on 2024-11-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_board_delete_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.AlterField(
            model_name='game',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('symbol', models.CharField(choices=[('X', 'X'), ('O', 'O')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
    ]
