# Generated by Django 5.1.2 on 2025-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_board_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='symbol',
            field=models.CharField(choices=[('X', 'X'), ('O', 'O')], max_length=1),
        ),
    ]
