# Generated by Django 5.1.2 on 2025-02-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_queryusers_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.TextField(default=""),
        ),
    ]
