# Generated by Django 5.1.2 on 2025-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="symbol",
            field=models.CharField(
                choices=[("X", "X"), ("O", "O"), ("Xw", "Xw"), ("Ow", "Ow")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="gamestatus",
            name="symbol",
            field=models.CharField(
                choices=[("X", "X"), ("O", "O"), ("Xw", "Xw"), ("Ow", "Ow")],
                max_length=2,
            ),
        ),
    ]
